import { provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import { importProvidersFrom, type ApplicationConfig } from '@angular/core';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideRouter } from '@angular/router';
import {
  ArrowLeft,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleX,
  ClipboardList,
  Clock3,
  History,
  Inbox,
  Info,
  LoaderCircle,
  LucideAngularModule,
  Menu,
  Minus,
  PackageCheck,
  PackageOpen,
  PackageSearch,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  ShoppingBag,
  ShoppingCart,
  Store,
  Trash2,
  Truck,
  UserRound,
  Users,
  Wifi,
  WifiOff,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideAnimations(),
    provideHttpClient(withInterceptorsFromDi()),
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowLeft,
        Check,
        CheckCircle2,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        CircleAlert,
        CircleX,
        ClipboardList,
        Clock3,
        History,
        Inbox,
        Info,
        LoaderCircle,
        Menu,
        Minus,
        PackageCheck,
        PackageOpen,
        PackageSearch,
        Plus,
        RefreshCw,
        RotateCcw,
        Search,
        ShoppingBag,
        ShoppingCart,
        Store,
        Trash2,
        Truck,
        UserRound,
        Users,
        Wifi,
        WifiOff,
        X,
      }),
    ),
  ],
};
