import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { importProvidersFrom, type ApplicationConfig } from '@angular/core';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideRouter } from '@angular/router';
import {
  ArrowLeft,
  ArrowRight,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleX,
  ClipboardList,
  Clock3,
  DatabaseBackup,
  FlaskConical,
  History,
  Inbox,
  Info,
  LoaderCircle,
  LockKeyhole,
  LucideAngularModule,
  Menu,
  Minus,
  PackageCheck,
  Package,
  PackageOpen,
  PackageSearch,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Store,
  Trash2,
  Truck,
  TriangleAlert,
  UserRound,
  UserRoundCog,
  Users,
  Wifi,
  WifiOff,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';
import { operatorContextInterceptor } from './core/api/operator-context.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideAnimations(),
    provideHttpClient(withInterceptors([operatorContextInterceptor])),
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowLeft,
        ArrowRight,
        Check,
        CheckCircle2,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        CircleAlert,
        CircleX,
        ClipboardList,
        Clock3,
        DatabaseBackup,
        FlaskConical,
        History,
        Inbox,
        Info,
        LoaderCircle,
        LockKeyhole,
        Menu,
        Minus,
        PackageCheck,
        Package,
        PackageOpen,
        PackageSearch,
        Plus,
        RefreshCw,
        RotateCcw,
        Search,
        ShieldCheck,
        ShoppingBag,
        ShoppingCart,
        Store,
        Trash2,
        Truck,
        TriangleAlert,
        UserRound,
        UserRoundCog,
        Users,
        Wifi,
        WifiOff,
        X,
      }),
    ),
  ],
};
